change yml replace base href

diff --git a/.github/workflows/dotnet.yaml b/.github/workflows/dotnet.yaml
--- a/.github/workflows/dotnet.yaml
+++ b/.github/workflows/dotnet.yaml
@@ -18,9 +18,22 @@ jobs:
     - name: Publish .NET Core Project
       run: dotnet publish "src/Blucrow.Foodtracker/Blucrow.Foodtracker.csproj" -c Release -o release --nologo
     
+    - name: Find and replace base href
+        run: |
+          # Find index.html.  GNU find is assumed.
+          HTML_FILE=$(find . -name "index.html" -print -quit)
+          if [ -z "$HTML_FILE" ]; then
+            echo "Error: index.html not found."
+            exit 1
+          fi
+          echo "Found index.html at $HTML_FILE"
+
+          # Use sed to replace the base href.
+          sed -i 's#<base href="/">#<base href="/Simplefoodtracker/">#g' "$HTML_FILE"
+          echo "Replaced base href in $HTML_FILE"
  
-    - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
-      run: sed -i 's/<base href="\/" \/>/<base href="\/Simplefoodtracker\/" \/>/g' release/wwwroot/index.html
+    #- name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
+    #  run: sed -i 's/<base href="\/" \/>/<base href="\/Simplefoodtracker\/" \/>/g' release/wwwroot/index.html
     
  
     - name: copy index.html to 404.html
